version: 2

updates:
    -   package-ecosystem: "npm"
        directory: "/"
        schedule:
            interval: "daily"
        open-pull-requests-limit: 10
        target-branch: "dev"
        ignore:
            -   dependency-name: "typescript"
            -   dependency-name: "@types/node"
            -   dependency-name: "@typescript/lib-dom"

    -   package-ecosystem: github-actions
        directory: "/"
        target-branch: "dev"
        schedule:
            interval: "weekly"
        open-pull-requests-limit: 10
