import type { ProjectContext } from './project-context.js';
import type { Type, TypeKind } from './models/type.js';
import type ts from 'typescript';


/**
 * Base specification of what a reflected node should have.
 */
export interface ReflectedNode<Model extends object = object, T extends ts.Node | ts.Signature = ts.Node> {
    /**
     * The original node generated by the TypeScript compiler
     */
    getTsNode(): T;

    /**
     * Returns the context in which the AST node was created.
     * The context contains useful utilities like the TS type checker.
     */
    getContext(): ProjectContext;

    /**
     * Returns a simple readonly JavaScript object
     * without methods or internal state.
     */
    serialize(): Model | Model[];
}

/**
 * Base specification of what a reflected type should have.
 */
export interface ReflectedType<T extends ts.TypeNode = ts.TypeNode> extends ReflectedNode<Type, T> {
    /**
     * The type representation as text
     */
    getText(): string;

    /**
     * The original type generated by the TypeScript compiler
     */
    getTsType(): ts.Type;

    /**
     * The kind of type (intersection, union, conditional, literal, etc...)
     */
    getKind(): TypeKind;
}
