name: 💡 Feature Request
description: Suggest an idea
title: 'feat: '
body:
    - type: checkboxes
      attributes:
          label: Prerequisites
          description: Please ensure you have completed all of the following.
          options:
              - label: I have read the [Contributing Guidelines](https://github.com/jordimarimon/ts-ast-parser/blob/main/CONTRIBUTING.md).
                required: true
              - label: I have searched for [existing issues](https://github.com/jordimarimon/ts-ast-parser/issues) that already report this problem, without success.
                required: true
    - type: textarea
      attributes:
          label: Describe the Feature Request
          description: A clear and concise description of what the feature does.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Describe the Use Case
          description: A clear and concise use case for what problem this feature would solve.
      validations:
          required: true
