name: Build and Test

on:
    push:
        branches: [ "dev" ]
    pull_request:
        branches: [ "dev" ]

jobs:
    analyse:
        if: ${{ github.actor != 'dependabot[bot]' }}
        name: Build
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read
            security-events: write
        strategy:
            matrix:
                node-version: [ 14.20.0, 16.x, 18.x ]
                ts-version: [ 4.7.2, 4.8.2, 4.9.4 ]
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Setup Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: Install latest NPM
                run: npm i -g npm@latest

            -   name: Install dependencies
                run: npm ci

            -   name: Set up the TypeScript version
                run: |
                    npm remove typescript
                    npm i -D -E typescript@${{ matrix.ts-version }}

            -   name: Build
                run: npm run build

            -   name: Run tests
                run: npm run test
